version: "3.9"
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ymera
      POSTGRES_USER: ymera
      POSTGRES_PASSWORD: ymera
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server","--save","60","1","--loglevel","warning"]
    ports: ["6379:6379"]

volumes:
  pgdata:
